<?xml version="1.0"?>

<robot name="UnoDopo_sim" xmlns:xacro="http://www.ros.org/wiki/xacro">
    <xacro:include filename="$(find urdf_tutorial)/urdf/uno_dopo_properties.urdf.xacro"/>

    <!-- main wheel macro -->
    <xacro:macro name="main_wheels" params="suffix reflect">
        <!-- This block provides the simulator (Gazebo) with information on a few additional
        physical properties. See http://gazebosim.org/tutorials/?tut=ros_urdf for more-->
        <gazebo reference="${suffix}_wheel">
          <mu1 value="200.0"/>
          <mu2 value="100.0"/>
          <kp value="10000000.0" />
          <kd value="1.0" />
          <material>Gazebo/Grey</material>
        </gazebo>

    </xacro:macro>

    <!-- create main two wheels -->
    <xacro:main_wheels suffix="right" reflect="1.0"/>
    <xacro:main_wheels suffix="left" reflect="-1.0"/>

    <gazebo reference="front_castor_wheel">
        <mu1 value="1.0"/>
        <mu2 value="1.0"/>
        <kp value="10000000.0" />
        <kd value="1.0" />
        <material>Gazebo/Grey</material>
    </gazebo>

    <!-- should contain a LINK name -->
    <gazebo reference="back_castor_wheel">
        <mu1 value="1.0"/>
        <mu2 value="1.0"/>
        <kp value="10000000.0" />
        <kd value="1.0" />
        <material>Gazebo/Grey</material>
    </gazebo>


    <!-- Gazebo plugin for ROS Control -->
    <!-- <gazebo>
      <plugin name="gazebo_ros_control" filename="libgazebo_ros_control.so">
        <robotNamespace>/</robotNamespace>
      </plugin>
    </gazebo> -->

    <!-- diff drive plugin -->
    <gazebo>
      <plugin name="uno_dopo_diff_driver" filename="libgazebo_ros_diff_drive.so">
      <commandTopic>cmd_vel</commandTopic>
      <odometryTopic>odom</odometryTopic>
      <odometryFrame>odom</odometryFrame>
      <odometrySource>world</odometrySource>
      <publishOdomTF>true</publishOdomTF>
      <robotBaseFrame>base_link</robotBaseFrame>
      <publishWheelTF>false</publishWheelTF>
      <publishTf>true</publishTf>
      <publishWheelJointState>true</publishWheelJointState>
      <legacyMode>false</legacyMode>
      <updateRate>30</updateRate>
      <leftJoint>left_wheel_joint</leftJoint>
      <rightJoint>right_wheel_joint</rightJoint>
      <wheelSeparation>${wheel_separation}</wheelSeparation>
      <wheelDiameter>${wheel_radius*2}</wheelDiameter>
      <wheelAcceleration>1</wheelAcceleration>
      <wheelTorque>10</wheelTorque>
      <rosDebugLevel>na</rosDebugLevel>
      </plugin>
    </gazebo>



</robot>
