<?xml version="1.0"?>

<robot name="UnoDopo_sim" xmlns:xacro="http://www.ros.org/wiki/xacro">
    <xacro:include filename="$(find unodopo_description)/urdf/unodopo_properties.urdf.xacro"/>

    <!-- main wheel macro -->
    <xacro:macro name="main_wheels" params="suffix reflect">
        <!-- This block provides the simulator (Gazebo) with information on a few additional
        physical properties. See http://gazebosim.org/tutorials/?tut=ros_urdf for more-->
        <gazebo reference="${suffix}_wheel">
          <mu1 value="200.0"/>
          <mu2 value="100.0"/>
          <kp value="10000000.0" />
          <kd value="1.0" />
          <material>Gazebo/Grey</material>
        </gazebo>

    </xacro:macro>

    <!-- create main two wheels -->
    <xacro:main_wheels suffix="right" reflect="1.0"/>
    <xacro:main_wheels suffix="left" reflect="-1.0"/>

    <gazebo reference="front_caster_wheel">
        <mu1 value="1.0"/>
        <mu2 value="1.0"/>
        <kp value="10000000.0" />
        <kd value="1.0" />
        <material>Gazebo/Grey</material>
    </gazebo>

    <!-- should contain a LINK name -->
    <gazebo reference="back_caster_wheel">
        <mu1 value="1.0"/>
        <mu2 value="1.0"/>
        <kp value="10000000.0" />
        <kd value="1.0" />
        <material>Gazebo/Grey</material>
    </gazebo>


    <!-- Gazebo plugin for ROS Control -->
    <!-- <gazebo>
      <plugin name="gazebo_ros_control" filename="libgazebo_ros_control.so">
        <robotNamespace>/</robotNamespace>
      </plugin>
    </gazebo> -->

    <!-- diff drive plugin -->
    <gazebo>
      <plugin name="uno_dopo_diff_driver" filename="libgazebo_ros_diff_drive.so">
      <commandTopic>cmd_vel</commandTopic>
      <odometryTopic>odom</odometryTopic>
      <odometryFrame>odom</odometryFrame>
      <odometrySource>world</odometrySource>
      <publishOdomTF>true</publishOdomTF>
      <robotBaseFrame>base_link</robotBaseFrame>
      <publishWheelTF>false</publishWheelTF>
      <publishTf>true</publishTf>
      <publishWheelJointState>true</publishWheelJointState>
      <legacyMode>false</legacyMode>
      <updateRate>30</updateRate>
      <leftJoint>left_wheel_joint</leftJoint>
      <rightJoint>right_wheel_joint</rightJoint>
      <wheelSeparation>${wheel_separation}</wheelSeparation>
      <wheelDiameter>${wheel_radius*2}</wheelDiameter>
      <wheelAcceleration>1</wheelAcceleration>
      <wheelTorque>10</wheelTorque>
      <rosDebugLevel>na</rosDebugLevel>
      </plugin>
    </gazebo>

    <gazebo>
      <plugin name="joint_state_publisher"
          filename="libgazebo_ros_joint_state_publisher.so">
          <jointName>front_caster_joint, back_caster_joint</jointName>
      </plugin>
    </gazebo>

    <!-- laser scan plugin -->
    <gazebo reference="laser_scan_link">
        <sensor type="ray" name="front_sick_lidar_sensor">
        <pose>0.0 0.3 0.2 0 0 0</pose>
        <visualize>true</visualize>
        <update_rate>24</update_rate>
        <ray>
          <scan>
            <horizontal>
              <samples>1080</samples>
              <resolution>0.25</resolution>
              <min_angle>-2.356</min_angle>
              <max_angle>2.356</max_angle>
            </horizontal>
          </scan>
          <range>
            <min>0.1</min>
            <max>10</max>
	          <resolution>0.01</resolution>
          </range>
          <noise>
            <type>gaussian</type>
            <mean>0.0</mean>
            <stddev>0.01</stddev>
          </noise>
        </ray>
        <plugin name="gazebo_ros_front_hokuyo_controller" filename="libgazebo_ros_laser.so">
        <topicName>/laser/scan</topicName>
        <frameName>laser_scan_link</frameName>
      </plugin>
    </sensor>
    <material>
        Gazebo/Orange
    </material>
    </gazebo>
</robot>
