<?xml version="1.0"?>
<robot name="UnoDopo" xmlns:xacro="http://www.ros.org/wiki/xacro">
    <xacro:include filename="$(find unodopo_description)/urdf/unodopo.gazebo.xacro"/>
<!--
    <link name="root">
    </link> -->

    <!-- base_link -->
    <link name="base_link">
        <visual>
            <material name="grey"/>
            <origin rpy="0 0 0" xyz=" 0.0 0.0 0.0"/>
            <geometry>
                <!-- <box size="${base_width}  ${base_length} ${base_height}"/> -->
                <mesh filename="package://unodopo_description/meshes/UnoDopoBase.obj" scale="1.0 1.0 1.0"/>
            </geometry>
        </visual>
        <inertial>
            <inertia ixx="0.0" ixy="0.0" ixz="0.0" iyy="${base_iyy}" iyz="0.0" izz="${base_izz}"/>
            <mass value="${base_mass}"/>
        </inertial>
    </link>

    <!-- <joint name="root" type="fixed">
        <parent link="root"/>
        <child link="base_link"/>
    </joint> -->

    <!-- main wheel macro -->
    <xacro:macro name="main_wheels" params="suffix reflect">

        <!-- main wheel link -->
        <link name="${suffix}_wheel">
            <collision>
                <geometry>
                     <cylinder radius="${wheel_radius}" length="${wheel_length}"/>
                </geometry>
            </collision>
            <visual>
                <!-- <origin rpy="${1.57} 0 0" /> -->
                <material name="black"/>
                <geometry>
                    <cylinder radius="${wheel_radius}" length="${wheel_length}"/>
                    <!-- <mesh filename="package://urdf_tutorial/meshes/UnoDopoWheel.obj" scale="${1.0} ${1.0} ${1.0}"/> -->
                </geometry>
            </visual>
            <inertial>
                <inertia ixx="${wheel_ixx}" ixy="0.0" ixz="0.1" iyy="${wheel_ixx}" iyz="0.0" izz="${wheel_izz}"/>
                <mass value="1.0"/>
            </inertial>
        </link>

        <!-- main wheel joint -->
        <joint name="${suffix}_wheel_joint" type="continuous">
            <parent link="base_link"/>
            <child link="${suffix}_wheel"/>
            <origin xyz="0 ${reflect*(wheel_separation+wheel_thickness*0)} ${wheel_radius-caster_wheel_radius}" rpy="-1.57 0 0"/>
            <axis xyz="0.0 0.0 1.0"/>
        </joint>


        <!-- This block connects the wheel joint to an actuator (motor), which informs both
        simulation and visualization of the robot -->
        <transmission name="${suffix}_wheel_trans">
          <type>transmission_interface/SimpleTransmission</type>
          <actuator name="${suffix}_wheel_motor">
            <mechanicalReduction>1</mechanicalReduction>
          </actuator>
          <joint name="${suffix}_wheel_joint">
            <hardwareInterface>VelocityJointInterface</hardwareInterface>
          </joint>
        </transmission>
    </xacro:macro>

    <!-- create main two wheels -->
    <xacro:main_wheels suffix="right" reflect="1.0"/>
    <xacro:main_wheels suffix="left" reflect="-1.0"/>

    <!-- caster wheels -->
    <link name="front_caster_wheel">
        <visual>
            <material name="black"/>
            <geometry>
                 <cylinder radius="${caster_wheel_radius}" length="${caster_wheel_length}"/>
            </geometry>
        </visual>
        <collision>
            <geometry>
                 <cylinder radius="${caster_wheel_radius}" length="${caster_wheel_length}"/>
            </geometry>
        </collision>
        <inertial>
            <inertia ixx="${caster_wheel_ixx}" ixy="0.0" ixz="0.0" iyy="${caster_wheel_ixx}" iyz="0.0" izz="${caster_wheel_izz}"/>
            <mass value="1.0"/>
        </inertial>
    </link>

    <joint name="front_caster_joint" type="continuous">
        <parent link="base_link"/>
        <child link="front_caster_wheel"/>
         <origin rpy="1.57 0 0" xyz="0.1625 0 0.0"/>
         <axis xyz="0.0 0.0 1.0"/>
    </joint>

    <link name="back_caster_wheel">
        <visual>
            <material name="black"/>
            <geometry>
                 <cylinder radius="${caster_wheel_radius}" length="${caster_wheel_length}"/>
            </geometry>
        </visual>
        <collision>
            <geometry>
                 <cylinder radius="${caster_wheel_radius}" length="${caster_wheel_length}"/>
            </geometry>
        </collision>
        <inertial>
            <inertia ixx="${caster_wheel_ixx}" ixy="0.0" ixz="0.0" iyy="${caster_wheel_ixx}" iyz="0.0" izz="${caster_wheel_izz}"/>
            <mass value="1.0"/>
        </inertial>
    </link>

    <joint name="back_caster_joint" type="continuous">
        <parent link="base_link"/>
        <child link="back_caster_wheel"/>
        <origin rpy="1.57 0 0" xyz="-0.1625 0 0.0"/>
        <axis xyz="0.0 0.0 1.0"/>
    </joint>

    <!-- lidar link -->
    <link name="laser_scan_link">
        <visual>
            <material name="hokuyo_laser_scanner_material"/>
            <geometry>
              <mesh filename="package://unodopo_description/meshes/hokuyo_laser_scanner.stl" scale="1.0 1.0 1.0"/>
            </geometry>
        </visual>
        <collision>
            <geometry>
              <mesh filename="package://unodopo_description/meshes/hokuyo_laser_scanner.stl" scale="1.0 1.0 1.0"/>
            </geometry>
        </collision>
		    <inertial>
		    	  <mass value="0.2" />
		    	  <inertia ixx="0" ixy="0"  ixz="0" iyy="0" iyz="0" izz="0" />
		    </inertial>
    </link>

    <joint name="laser_scan_joint" type="fixed">
        <origin xyz="${lidar_horizontal_pos} 0 ${lidar_height}" rpy="0.0 0.0 0"/>
        <parent link="base_link"/>
        <child link="laser_scan_link"/>
    </joint>

</robot>
